const NotesActionsTypes = {
    FETCH_NOTES_REQUEST: "NOTES/FETCH_NOTES_REQUEST",
    FETCH_NOTES_ERROR: "NOTES/FETCH_NOTES_ERROR",
    FETCH_NOTES_SUCCESS: "NOTES/FETCH_NOTES_SUCCESS",
    FETCH_NOTE_BY_ID_REQUEST: "NOTES/FETCH_NOTE_BY_ID_REQUEST",
    FETCH_NOTE_BY_ID_ERROR: "NOTES/FETCH_NOTE_BY_ID_ERROR",
    FETCH_NOTE_BY_ID_SUCCESS: "NOTES/FETCH_NOTE_BY_ID_SUCCESS",
    UPDATE_NOTE_REQUEST: "NOTES/UPDATE_NOTE_REQUEST",
    UPDATE_NOTE_ERROR: "NOTES/UPDATE_NOTE_ERROR",
    UPDATE_NOTE_SUCCESS: "NOTES/UPDATE_NOTE_SUCCESS",
    CREATE_NOTE_REQUEST: "NOTES/CREATE_NOTE_REQUEST",
    CREATE_NOTE_ERROR: "NOTES/CREATE_NOTE_ERROR",
    CREATE_NOTE_SUCCESS: "NOTES/CREATE_NOTE_SUCCESS",
  };
  
  export default NotesActionsTypes;
  