const UsersActionsTypes = {
  FETCH_USERS_REQUEST: "USERS/FETCH_USERS_REQUEST",
  FETCH_USERS_ERROR: "USERS/FETCH_USERS_ERROR",
  FETCH_USERS_SUCCESS: "USERS/FETCH_USERS_SUCCESS",
  FETCH_MOST_MENTIONED_REQUEST: "USERS/FETCH_MOST_MENTIONED_REQUEST",
  FETCH_MOST_MENTIONED_ERROR: "USERS/FETCH_MOST_MENTIONED_ERROR",
  FETCH_MOST_MENTIONED_SUCCESS: "USERS/FETCH_MOST_MENTIONED_SUCCESS",
};

export default UsersActionsTypes;
